import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const read=p=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const json=p=>JSON.parse(read(p));
const manifest=json('src/data/ALEX_REVIEWED_MEDIA_20261003.json');
const snapshot=json('src/data/ALL_CHARACTER_RELEASE_FIXTURE_20261004.json');
const handoff=json('src/data/ALEX_ID_LEVEL_HANDOFF_20261006.json');
const media=manifest.clips.map(c=>({id:`alex-reviewed-${c.move_slug}`,moveId:c.move_id,status:'approved_for_preview',mediaType:'video',mediaUrl:c.media_url,posterUrl:c.poster_url}));
function moduleFor(owner=handoff, clips=media){const m={exports:{}};new Function('module','exports','require',ts.transpileModule(read('src/lib/alex-approved-data-overlay.ts'),{compilerOptions:{esModuleInterop:true,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m,m.exports,n=>({'@/data/ALL_CHARACTER_RELEASE_FIXTURE_20261004.json':snapshot,'@/data/ALEX_ID_LEVEL_HANDOFF_20261006.json':owner,'@/data/ALEX_REVIEWED_MEDIA_20261003.json':manifest,'@/lib/alex-reviewed-media':{ALEX_CHARACTER_ID:snapshot.characters.alex.characterId,getAlexReviewedMedia:()=>clips}}[n]));return m.exports;}
const base=()=>({guideSections:[],combos:[],setups:[],sequences:[],matchups:[],training:[],moves:structuredClone(snapshot.characters.alex.moves)});
test('64 base remains, six latest media pass and BAD_CUT SA2 stays hold',()=>{const b=base(),saved=structuredClone(b),out=moduleFor().overlayAlexReviewedMedia(b,media);assert.equal(out.moves.length,64);assert.equal(out.moves.filter(m=>m.media).length,6);assert.equal(out.moves.find(m=>m.id===handoff.moves.find(m=>m.mediaStatus==='BAD_CUT_HOLD').id).media,null);assert.deepEqual(b,saved);for(let i=0;i<64;i++){const {media:_,...a}=out.moves[i];const {media:__,...before}=b.moves[i];assert.deepEqual(a,before);}});
test('seven overlay supported only with seven explicitly ready identity records',()=>{const owner=structuredClone(handoff);owner.moves.forEach(m=>{if(manifest.moves.some(x=>x.id===m.id))m.mediaStatus='READY_REUSED';});const out=moduleFor(owner).overlayAlexReviewedMedia(base(),media);assert.equal(out.moves.filter(m=>m.media).length,7);assert.equal(out.moves.filter(m=>!m.media).length,57);});
test('ID slug category command conflicts and duplicates deny media only',()=>{for(const mutation of [m=>m.id='wrong',m=>m.slug='wrong',m=>m.moveType='normal',m=>m.commands[0].numericNotation='wrong']){const b=base();mutation(b.moves.find(m=>m.id===manifest.moves[1].id));const out=moduleFor().overlayAlexReviewedMedia(b,media);assert.equal(out.moves.filter(m=>m.media).length,5);assert.equal(out.moves.length,64);}assert.equal(moduleFor().overlayAlexReviewedMedia(base(),[...media,media[1]]).moves.filter(m=>m.media).length,5);});
test('no clips preserves all frames and commands with safe fallback',()=>{const b=base();const out=moduleFor().overlayAlexReviewedMedia(b,[]);assert.equal(out.moves.length,64);assert.ok(out.moves.every(m=>m.media===null));assert.deepEqual(out.moves.map(m=>[m.frame,m.commands]),b.moves.map(m=>[m.frame,m.commands]));});
test('production and wrong character cannot use draft Alex base',()=>{const previous=process.env.VERCEL_ENV;try{process.env.VERCEL_ENV='production';assert.equal(moduleFor().getAlexFullDataWithReviewedMedia(snapshot.characters.alex.characterId),null);process.env.VERCEL_ENV='preview';assert.equal(moduleFor().getAlexFullDataWithReviewedMedia('wrong'),null);const bundle=moduleFor().getAlexFullDataWithReviewedMedia(snapshot.characters.alex.characterId);assert.equal(bundle.moves.length,64);assert.equal(bundle.moves.filter(m=>m.media).length,6);}finally{if(previous===undefined)delete process.env.VERCEL_ENV;else process.env.VERCEL_ENV=previous;}});
