import test from 'node:test';
import assert from 'node:assert/strict';
import { classifyCombo, duplicateCandidateMap } from '../scripts/lib/combo-publication-readiness.mjs';
const source = { relationship:'reference', source:{title:'Primary source',url:'https://example.test/combo',publisher:'Author',reliability_level:'primary'} };
const row = {id:'1',slug:'test',name:'Test',notation:'5LP > 236HP',character_id:'ryu',valid_from_patch_id:'current',valid_to_patch_id:null,status:'draft',verification_status:'verified',position:'mid',conditions:'standing hit',starter_text:'5LP',damage:null,drive_cost:null,sa_cost:null,notes:'',game_verification:{result:'pass',patch_id:'current',recording_url:'https://example.test/recording',verified_by:'reviewer',verified_at:'2026-09-30'}};
function classify(overrides={}, contextOverrides={}) { return classifyCombo({...row,...overrides}, {tokenize:raw=>[{raw,type:'TEXT'}],characters:new Map([['ryu',{slug:'ryu',status:'published',is_playable:true}]]),patches:new Map([['current',{id:'current',is_current:true}]]),sourcesByCombo:new Map([['1',[source]]]),duplicateCandidates:new Map(),ids:new Set(['1','2']),...contextOverrides}); }
test('publishable requires explicit reproduction evidence and source, not status alone',()=>{ assert.equal(classify().classification,'PUBLISHABLE');assert.equal(classify({game_verification:null}).classification,'GAME_VERIFICATION_REQUIRED'); });
test('source absence is primary but game failure remains secondary',()=>{const r=classify({game_verification:null},{sourcesByCombo:new Map()});assert.equal(r.classification,'SOURCE_REQUIRED');assert.ok(r.secondary_reasons.some(r=>r.code==='CURRENT_GAME_REPRODUCTION_NOT_DOCUMENTED'));});
test('verified status does not override conflicting notes or placeholder recipe',()=>{assert.equal(classify({notes:'Do not publish until training verification'}).classification,'GAME_VERIFICATION_REQUIRED');assert.equal(classify({notation:'Training verification required'}).classification,'GAME_VERIFICATION_REQUIRED');});
test('missing optional numerics remain unknown while negative supplied values are errors',()=>{assert.equal(classify().checks.missing_optional_numeric.length,3);assert.equal(classify({damage:-1}).classification,'DATA_ERROR');});
test('stale patch and archived rows remain HOLD despite other complete proof',()=>{assert.equal(classify({valid_to_patch_id:'old'}).classification,'HOLD');assert.equal(classify({status:'archived'}).classification,'HOLD');});
test('candidate source, missing publisher and nonHTTPS source cannot be ready',()=>{for(const s of [{...source,relationship:'candidate'},{...source,source:{...source.source,publisher:''}},{...source,source:{...source.source,url:'http://example.test'}}])assert.equal(classify({}, {sourcesByCombo:new Map([['1',[s]]])}).classification,'SOURCE_REQUIRED');});
test('identical notation is a candidate only, not a confirmed duplicate',()=>{const map=duplicateCandidateMap([row,{...row,id:'2',conditions:'corner'}]);assert.deepEqual(map.get('1'),['2']);assert.notEqual(classify({}, {duplicateCandidates:map}).classification,'DUPLICATE');assert.equal(classify({duplicate_of:'2'}).classification,'DUPLICATE');});
test('different strength or character does not merge duplicate candidates',()=>{assert.equal(duplicateCandidateMap([row,{...row,id:'2',notation:'5LP > 236LP'},{...row,id:'3',character_id:'ken'}]).size,0);});
