import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const snapshot=JSON.parse(read('src/data/ALL_CHARACTER_RELEASE_FIXTURE_20261004.json'));
const checkpoint=JSON.parse(read('src/data/NINE_CHARACTER_PAGE_CANDIDATE_20261006.json'));
const manifest=JSON.parse(read('src/data/ALEX_REVIEWED_MEDIA_20261003.json'));
const handoff=JSON.parse(read('src/data/ALEX_ID_LEVEL_HANDOFF_20261006.json'));
const clips=manifest.clips.map(c=>({id:`alex-reviewed-${c.move_slug}`,moveId:c.move_id,status:'approved_for_preview',mediaType:'video',mediaUrl:c.media_url,posterUrl:c.poster_url}));
function moduleFor(path,deps){const m={exports:{}};new Function('module','exports','require',ts.transpileModule(read(path),{compilerOptions:{esModuleInterop:true,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m,m.exports,n=>{assert.ok(n in deps,n);return deps[n];});return m.exports;}
const alex=moduleFor('src/lib/alex-approved-data-overlay.ts',{'@/data/ALL_CHARACTER_RELEASE_FIXTURE_20261004.json':snapshot,'@/data/ALEX_ID_LEVEL_HANDOFF_20261006.json':handoff,'@/data/ALEX_REVIEWED_MEDIA_20261003.json':manifest,'@/lib/alex-reviewed-media':{ALEX_CHARACTER_ID:snapshot.characters.alex.characterId,getAlexReviewedMedia:()=>clips}});
function load(pack=checkpoint){return moduleFor('src/lib/nine-character-integration-candidate.ts',{'@/data/NINE_CHARACTER_PAGE_CANDIDATE_20261006.json':pack,'@/data/ALL_CHARACTER_RELEASE_FIXTURE_20261004.json':snapshot,'@/lib/alex-approved-data-overlay':alex}).getNineCharacterIntegrationCandidate;}
const old=process.env.VERCEL_ENV;
test.after(()=>{if(old===undefined)delete process.env.VERCEL_ENV;else process.env.VERCEL_ENV=old;});
for(const slug of Object.keys(checkpoint.candidate.characters))test(`${slug} snapshot candidate retains IDs, accepted values and pending reason sidecar`,()=>{process.env.VERCEL_ENV='preview';const saved=structuredClone(snapshot);const out=load()(snapshot.characters[slug].characterId,slug);assert.ok(out);assert.equal(out.preservedBase.length,snapshot.characters[slug].moves.length);assert.equal(out.bundle.moves.length,out.preservedBase.length-(slug==='alex'?1:0));for(const m of out.bundle.moves){assert.deepEqual(Object.fromEntries(Object.entries(m.frame).filter(([k])=>k!=='verificationStatus')),checkpoint.candidate.characters[slug].find(r=>r.id===m.id).frame);assert.equal(m.frame.verificationStatus,snapshot.characters[slug].moves.find(r=>r.id===m.id).frame?.verificationStatus??'unverified');assert.equal(m.releaseFixture,true);assert.ok(m.commands.every(c=>c.moveId===m.id));assert.ok(out.evidence[m.id]);}assert.deepEqual(snapshot,saved);assert.equal(out.productionApproved,false);});
test('Alex retains immutable 64 base, displays safe 63 with 6 media, SA2 fallback',()=>{process.env.VERCEL_ENV='preview';const out=load()(snapshot.characters.alex.characterId,'alex');assert.deepEqual(out.preservedBase.map(m=>[m.id,m.frame,m.commands]),snapshot.characters.alex.moves.map(m=>[m.id,m.frame,m.commands]));assert.equal(out.bundle.moves.filter(m=>m.media).length,6);assert.equal(out.bundle.moves.find(m=>m.id==='fd27f911-987b-4ba0-b727-e73301ffeb69').media,null);assert.ok(!out.bundle.moves.some(m=>m.id==='7b009800-5747-4b7d-a2c1-7163f1826d48'));});
test('Production development missing sidecar duplicate identity and unmasked value fail closed',()=>{for(const env of ['production','development']){process.env.VERCEL_ENV=env;assert.equal(load()(snapshot.characters.alex.characterId,'alex'),null);}process.env.VERCEL_ENV='preview';for(const change of [p=>delete p.evidence[p.candidate.characters.alex[0].id],p=>p.candidate.characters.alex[0].frame.startup=22,p=>p.candidate.characters.alex[1].id=p.candidate.characters.alex[0].id]){const p=structuredClone(checkpoint);change(p);assert.equal(load(p)(snapshot.characters.alex.characterId,'alex'),null);}});
test('Nine Preview selection keeps registry empty and unmaterialized media isolated',()=>{assert.match(read('src/lib/character-detail-data.ts'),/hasNineCharacterIntegrationCandidate\(slug\) && process.env.VERCEL_ENV === "preview"/);assert.deepEqual(JSON.parse(read('src/data/CHARACTER_PRODUCTION_RELEASE_APPROVAL.json')).characters,[]);process.env.VERCEL_ENV='preview';for(const slug of Object.keys(checkpoint.candidate.characters).filter(s=>s!=='alex'))assert.ok(load()(snapshot.characters[slug].characterId,slug).bundle.moves.every(m=>m.media===null));});

test('Alex contract explicitly separates 64 stored IDs, 63 candidate IDs and one recoverable hold',()=>{process.env.VERCEL_ENV='preview';const out=load()(snapshot.characters.alex.characterId,'alex');assert.deepEqual(out.counts,{dataBase:64,publicCandidate:63,held:1});assert.equal(out.frameStatus,'CURRENT_OFFICIAL_SNAPSHOT_ACCEPTED_WITH_PENDING');assert.equal(out.heldMoves[0].reviewStatus,'IDENTITY_REVIEW_REQUIRED');assert.equal(out.heldMoves[0].move.id,'7b009800-5747-4b7d-a2c1-7163f1826d48');assert.deepEqual(new Set([...out.bundle.moves.map(m=>m.id),...out.heldMoves.map(h=>h.move.id)]),new Set(out.preservedBase.map(m=>m.id)));});
test('held identity can return only after sidecar owner marks it included; unknown state denies',()=>{process.env.VERCEL_ENV='preview';const p=structuredClone(checkpoint),id='7b009800-5747-4b7d-a2c1-7163f1826d48';p.evidence[id].move_display='UNKNOWN';assert.equal(load(p)(snapshot.characters.alex.characterId,'alex'),null);p.evidence[id].move_display='INCLUDE_SAVED_IDENTITY';const synthetic=load(p)(snapshot.characters.alex.characterId,'alex');assert.deepEqual(synthetic.counts,{dataBase:64,publicCandidate:64,held:0});assert.equal(checkpoint.evidence[id].move_display,'SUPPRESS_PENDING_OFFICIAL_IDENTITY');});
test('real Preview resolver selects 63 Alex candidates with accepted frame, held ID absent and six media',async()=>{process.env.VERCEL_ENV='preview';const calls=[];const candidate={getNineCharacterIntegrationCandidate:load(),hasNineCharacterIntegrationCandidate:s=>Object.hasOwn(checkpoint.candidate.characters,s)};const resolver=moduleFor('src/lib/character-detail-data.ts',{'@/lib/nine-character-integration-candidate':candidate,'@/lib/production-character-approval':{getCharacterProductionApproval:()=>null},'@/lib/release-character-move-resolver':{},'@/lib/generated-release-fixture':{},'@/lib/device-preview':{},'@/lib/character-detail-v21-fixture':{},'@/lib/character-detail-route':{},'@/lib/supabase/server':{getSupabaseServerClient:()=>{calls.push('DB');throw Error('DB not permitted');}},'@/lib/public-move-gate':{},'@/lib/yasmine-move-media-pilot':{},'@/lib/public-source-links':{}});const id=snapshot.characters.alex.characterId;const resolved=await resolver.resolveCharacterDetailData(id,'alex',null);assert.equal(resolved.source,'fixture');assert.equal(resolved.bundle.moves.length,63);assert.equal(resolved.bundle.moves.filter(m=>m.media).length,6);assert.ok(resolved.bundle.moves.some(m=>m.frame.startup!==null));assert.ok(!resolved.bundle.moves.some(m=>m.id==='7b009800-5747-4b7d-a2c1-7163f1826d48'));assert.deepEqual(calls,[]);assert.deepEqual(await resolver.resolveCharacterDetailData('wrong','alex',null),{bundle:null,source:'unavailable'});process.env.VERCEL_ENV='production';assert.deepEqual(await resolver.resolveCharacterDetailData(id,'alex',null),{bundle:null,source:'unavailable'});});

test('official snapshot policy adopts exactly2919 cells while408 N/A and81 pending cells remain null',()=>{let accepted=0,na=0,pending=0;for(const [slug,rows] of Object.entries(checkpoint.candidate.characters))for(const row of rows)for(const [field,value] of Object.entries(row.frame)){const fact=checkpoint.evidence[row.id].frame_classifications[field];if(fact.status==='CURRENT_OFFICIAL_SNAPSHOT_ACCEPTED'){accepted++;assert.equal(fact.battle_version_label_verified,false);assert.equal(fact.capture_date,'2026-10-06');assert.equal(value,fact.value);}else{assert.equal(value,null);if(fact.status==='OFFICIAL_NA')na++;else pending++;}}assert.deepEqual({accepted,na,pending},{accepted:2919,na:408,pending:81});});
test('missing source, changed evidence, missing guard, fabricated N/A value and false battle version claim deny candidate',()=>{process.env.VERCEL_ENV='preview';for(const edit of [f=>f.source_available='NO',f=>f.evidence_value=987654,f=>f.source_field_guard_sha256='',f=>f.battle_version_label_verified=true]){const p=structuredClone(checkpoint),r=p.candidate.characters.alex.find(r=>p.evidence[r.id].frame_classifications.startup.status==='CURRENT_OFFICIAL_SNAPSHOT_ACCEPTED');edit(p.evidence[r.id].frame_classifications.startup);assert.equal(load(p)(snapshot.characters.alex.characterId,'alex'),null);}const p=structuredClone(checkpoint),r=p.candidate.characters.alex.find(r=>p.evidence[r.id].frame_classifications.onBlock.status==='OFFICIAL_NA');r.frame.onBlock='0';assert.equal(load(p)(snapshot.characters.alex.characterId,'alex'),null);});
test('all nine real Preview resolver selections retain567 display IDs without DB queries, Production denies every character',async()=>{process.env.VERCEL_ENV='preview';const resolver=moduleFor('src/lib/character-detail-data.ts',{'@/lib/nine-character-integration-candidate':{getNineCharacterIntegrationCandidate:load(),hasNineCharacterIntegrationCandidate:s=>Object.hasOwn(checkpoint.candidate.characters,s)},'@/lib/production-character-approval':{getCharacterProductionApproval:()=>null},'@/lib/release-character-move-resolver':{},'@/lib/generated-release-fixture':{},'@/lib/device-preview':{},'@/lib/character-detail-v21-fixture':{},'@/lib/character-detail-route':{},'@/lib/supabase/server':{getSupabaseServerClient:()=>{throw Error('DB not permitted');}},'@/lib/public-move-gate':{},'@/lib/yasmine-move-media-pilot':{},'@/lib/public-source-links':{}});let total=0;for(const slug of Object.keys(checkpoint.candidate.characters)){const out=await resolver.resolveCharacterDetailData(snapshot.characters[slug].characterId,slug,'arbitrary-token');assert.equal(out.source,'fixture');total+=out.bundle.moves.length;assert.deepEqual(await resolver.resolveCharacterDetailData('wrong',slug,null),{bundle:null,source:'unavailable'});}assert.equal(total,567);process.env.VERCEL_ENV='production';for(const slug of Object.keys(checkpoint.candidate.characters))assert.deepEqual(await resolver.resolveCharacterDetailData(snapshot.characters[slug].characterId,slug,null),{bundle:null,source:'unavailable'});});
