create index if not exists character_guide_sections_character_id_idx on public.character_guide_sections(character_id);
create index if not exists character_guide_sections_valid_from_patch_id_idx on public.character_guide_sections(valid_from_patch_id);
create index if not exists character_guide_sections_valid_to_patch_id_idx on public.character_guide_sections(valid_to_patch_id);
create index if not exists moves_character_id_idx on public.moves(character_id);
create index if not exists move_commands_move_id_idx on public.move_commands(move_id);
create index if not exists move_frame_data_move_id_idx on public.move_frame_data(move_id);
create index if not exists move_frame_data_valid_from_patch_id_idx on public.move_frame_data(valid_from_patch_id);
create index if not exists move_frame_data_valid_to_patch_id_idx on public.move_frame_data(valid_to_patch_id);
create index if not exists combos_character_id_idx on public.combos(character_id);
create index if not exists combos_valid_from_patch_id_idx on public.combos(valid_from_patch_id);
create index if not exists combos_valid_to_patch_id_idx on public.combos(valid_to_patch_id);
create index if not exists combo_moves_move_id_idx on public.combo_moves(move_id);
create index if not exists setups_character_id_idx on public.setups(character_id);
create index if not exists setups_valid_from_patch_id_idx on public.setups(valid_from_patch_id);
create index if not exists setups_valid_to_patch_id_idx on public.setups(valid_to_patch_id);
create index if not exists setup_moves_move_id_idx on public.setup_moves(move_id);
create index if not exists sequences_character_id_idx on public.sequences(character_id);
create index if not exists sequences_valid_from_patch_id_idx on public.sequences(valid_from_patch_id);
create index if not exists sequences_valid_to_patch_id_idx on public.sequences(valid_to_patch_id);
create index if not exists counters_defender_character_id_idx on public.counters(defender_character_id);
create index if not exists counters_opponent_character_id_idx on public.counters(opponent_character_id);
create index if not exists counters_valid_from_patch_id_idx on public.counters(valid_from_patch_id);
create index if not exists counters_valid_to_patch_id_idx on public.counters(valid_to_patch_id);
create index if not exists trainings_player_character_id_idx on public.trainings(player_character_id);
create index if not exists trainings_dummy_character_id_idx on public.trainings(dummy_character_id);
create index if not exists trainings_valid_from_patch_id_idx on public.trainings(valid_from_patch_id);
create index if not exists trainings_valid_to_patch_id_idx on public.trainings(valid_to_patch_id);
create index if not exists player_characters_character_id_idx on public.player_characters(character_id);
create index if not exists player_characters_valid_from_patch_id_idx on public.player_characters(valid_from_patch_id);
create index if not exists player_characters_valid_to_patch_id_idx on public.player_characters(valid_to_patch_id);
create index if not exists tournament_results_player_id_idx on public.tournament_results(player_id);
create index if not exists matches_tournament_id_idx on public.matches(tournament_id);
create index if not exists matches_winner_player_id_idx on public.matches(winner_player_id);
create index if not exists matches_video_id_idx on public.matches(video_id);
create index if not exists match_participants_player_id_idx on public.match_participants(player_id);
create index if not exists match_participants_character_id_idx on public.match_participants(character_id);
create index if not exists entity_sources_source_id_idx on public.entity_sources(source_id);
create index if not exists diagnosis_questions_diagnosis_id_idx on public.diagnosis_questions(diagnosis_id);
create index if not exists diagnosis_options_question_id_idx on public.diagnosis_options(question_id);
create index if not exists diagnosis_results_user_id_idx on public.diagnosis_results(user_id);
create index if not exists diagnosis_results_diagnosis_id_idx on public.diagnosis_results(diagnosis_id);
create index if not exists favorites_user_id_idx on public.favorites(user_id);

create index if not exists characters_status_order_idx on public.characters(status, display_order);
create index if not exists moves_status_character_idx on public.moves(status, character_id, display_order);
create index if not exists players_status_name_idx on public.players(status, display_name);
create index if not exists combos_status_character_idx on public.combos(status, character_id);
create index if not exists diagnoses_status_order_idx on public.diagnoses(status, display_order);
